# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-service
#   namespace: k8s-lbtest
# spec:
#   type: ClusterIP
#   ports:
#     - port: 80
#       targetPort: 80
#       protocol: TCP
#   selector:
#     app: nginx
#
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: k8s-lbtest
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: k8s-lbtest
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: nginx-config
            namespace: k8s-lbtest
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: k8s-lbtest
data:
  index.html: |
    <html>
      <head>
        <title>Welcome to nginx!</title>
      </head>
      <body>
        <h1>Welcome to nginx!</h1>
        <p>If you see this page, the nginx web server is successfully installed and working. Further configuration is required.</p>
      </body>
    </html>